config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main_view#index"

  namespace :turbo_showcase do
    resources :updating_methods do
      collection do
        post :happy_mood
        post :sad_mood
      end
    end
    resources :replacing_methods do
      collection do
        post :happy_mood
        post :sad_mood
      end
    end
    resources :appending_methods do
      collection do
        post :another_one
        post :sober
      end
    end
    resources :prepending_methods do
      collection do
        post :another_one
        post :sober
      end
    end
    resources :removing_methods do
      collection do
        post :disappear
        post :appear
      end
    end
  end
end

app/controllers/turbo_showcase/replacing_methods_controller.rb
# frozen_string_literal: true

module TurboShowcase
  class ReplacingMethodsController < ApplicationController
    def index
      main_folder_for_views = "#{Rails.root}/app/views/turbo_showcase/replacing_methods/"
      component_views = "#{main_folder_for_views}/components"

      @index_html = File.open("#{main_folder_for_views}/index.html.erb").read
      @div_with_id_html = File.open("#{component_views}/div_with_id.html.erb").read
      @happy_mood_file_html = File.open("#{component_views}/_happy_mood.html.erb").read
      @sad_mood_file_html = File.open("#{component_views}/_sad_mood.html.erb").read

      @controller_file_ruby =
        File.open("#{Rails.root}/app/controllers/turbo_showcase/replacing_methods_controller.rb").read
    end

    def sad_mood
      render turbo_stream: turbo_stream.replace("some-id-for-replace",
                                               partial: "turbo_showcase/replacing_methods/components/happy_mood")
    end

    def happy_mood
      render turbo_stream: turbo_stream.replace("some-id-for-replace",
                                               partial: "turbo_showcase/replacing_methods/components/sad_mood")
    end
  end
end

app/views/turbo_showcase/replacing_methods/components/_happy_mood.html.erb
<div id="some-id-for-replace">

  <div class="flex column">
    <%= form_with scope: :q, url: happy_mood_turbo_showcase_replacing_methods_path, data: { turbo: true, turbo_method: :post },
                  class: "space-y-8 divide-y divide-gray-200" do |f| %>
      <img style=" width: 300px; height: 300px" src="https://i.ytimg.com/vi/XpXRIM24Vzk/hqdefault.jpg"/>
        <p>Have a great day </p>
        <%= f.submit "Change moods", { class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" } %>
    <% end %>
  </div>
</div>

app/views/turbo_showcase/replacing_methods/components/_sad_mood.html.erb
<div id="some-id-for-replace">
  <div class="flex column">
    <%= form_with scope: :q, url: sad_mood_turbo_showcase_replacing_methods_path, data: { turbo: true, turbo_method: :post },
                  class: "space-y-8 divide-y divide-gray-200" do |f| %>
      <img style=" width: 300px; height: 300px" src="https://i.kym-cdn.com/photos/images/newsfeed/002/069/850/076.jpg"/>
      <p>Have a bad day </p>
      <%= f.submit "Change moods", { class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" } %>
    <% end %>
  </div>
</div>

app/views/turbo_showcase/replacing_methods/components/div_with_id.html.erb
<div id="some-id-for-replace">
  <%= render partial: "turbo_showcase/replacing_methods/components/happy_mood" %>
</div>