config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main_view#index"

  namespace :turbo_showcase do
    resources :updating_methods do
      collection do
        post :happy_mood
        post :sad_mood
      end
    end
    resources :replacing_methods do
      collection do
        post :happy_mood
        post :sad_mood
      end
    end
    resources :appending_methods do
      collection do
        post :another_one
        post :sober
      end
    end
    resources :prepending_methods do
      collection do
        post :another_one
        post :sober
      end
    end
    resources :removing_methods do
      collection do
        post :disappear
        post :appear
      end
    end
  end
end

app/controllers/turbo_showcase/removing_methods_controller.rb
# frozen_string_literal: true

module TurboShowcase
  class RemovingMethodsController < ApplicationController
    def index
      main_folder_for_views = "#{Rails.root}/app/views/turbo_showcase/removing_methods"
      @index_html = File.open("#{main_folder_for_views}/index.html.erb").read
      @div_with_id_html = File.open("#{main_folder_for_views}/components/div_with_id.html.erb").read

      @controller_file_ruby =
        File.open("#{Rails.root}/app/controllers/turbo_showcase/removing_methods_controller.rb").read
    end

    def disappear
      render turbo_stream: turbo_stream.remove("some-id-for-remove")
    end

    def appear
      render turbo_stream: turbo_stream.replace("some-id-for-replace",
                                                template: "turbo_showcase/removing_methods/components/div_with_id")
    end
  end
end

app/views/turbo_showcase/removing_methods/components/div_with_id.html.erb
<style>
  .some-div {
    width: 500px;
    height: 500px;
    background-image: url("/assets/background_dissapear.png");
    background-position: center;
  }
</style>
<div id="some-id-for-replace">
  <div class="flex flex-col">
    <div class="relative some-div">
      <img id="some-id-for-remove" class="relative" src="<%= asset_url("dissapear") %> " width="300" height="300" style="top: 41%; left: 6%"/>
    </div>
    <div class="flex">
      <%= form_with scope: :q, url: disappear_turbo_showcase_removing_methods_path, data: { turbo: true, turbo_method: :post },
                    class: "space-y-8 divide-y divide-gray-200" do |f| %>
        <%= f.submit "Dissapear", { class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" } %>
      <% end %>

      <%= form_with scope: :q, url: appear_turbo_showcase_removing_methods_path, data: { turbo: true, turbo_method: :post },
                    class: "space-y-8 divide-y divide-gray-200" do |f| %>
        <%= f.submit "Appear", { class: "bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" } %>
      <% end %>
    </div>
  </div>
</div>